### ISSUE TITLE
JSONModel.getProperty return type tagged as void

### ISSUE THREAD

**Issue by tiagobalmeida** [lmcarreiro/ui5ts#3]
Hi!,

It seems if you do this on a controller
`
var m = this.getView().getModel("a");
var some_string = m.getProperty("/someProp");
`
you'll get an error saying some_string is type void so can't do anything with it. Am I missing something? Was expecting getProperty to return "any" but this is not what's defined in the sap.d.ts.

Thanks a lot! This is a great project :)

**Comment by lmcarreiro** [comment]
It's because `sap.ui.model.json.JSONModel` inherits `sap.ui.model.Model` that "returns" `void` based on the API docs: https://sapui5.hana.ondemand.com/#/api/sap.ui.model.Model/methods/getProperty

In cases like this, to avoid TypeScript errors, if the return type of the method in the extended class doesn't match or inherits the return type of the overrided method in its base class, I need to override the return type of this method in the extended class to match the return type of the method in the base class.

But to avoid issues like this, I think that the easiest solution is to simply check all methods if their name starts with "get" and if their return type are `void`. If so, I'll replace their return type with `any`.

I'll try to put a version with this change tomorrow.

**Comment by lmcarreiro** [comment]
Fixed in `ui5ts@0.3.2`. Sorry about the delay.
